### ISSUE TITLE
Problem with munki conditional

### ISSUE THREAD

**Issue by patgmac** [macadmins/escrow-buddy#15]
When running the conditional/fact provided here: https://github.com/macadmins/escrow-buddy/wiki/Munki#conditional-item, and then run `sudo /usr/local/munki/conditions/munki_facts.py` I get the error "Error module 'escrow_buddy_needed' has no attribute 'fact' in file /usr/local/munki/conditions/facts/escrow_buddy_needed.py", and the result does not end up in ManagedInstallReport.plist.

**Comment by homebysix** [comment]
Thanks for flagging. I updated the conditional; check again now?

**Comment by patgmac** [comment]
Works, great. Thank you for the quick turnaround!
