### ISSUE TITLE
Authorization check script in wiki

### ISSUE THREAD

**Issue by patgmac** [macadmins/escrow-buddy#16]
Authorization check script https://github.com/macadmins/escrow-buddy/wiki/Munki#authorization-database-maintenance has a line `exec 2&gt;/dev/null`, not sure what that's supposed to do but the shell doesn't like it. 

Also, can the installcheck_script do without the <string> and </string> in the section with `grep -q '<string>Escrow Buddy:Invoke,privileged</string>`? Both MunkiAdmin and PlistEdit Pro complain about that.

**Comment by homebysix** [comment]
The `exec 2&gt;/dev/null` redirects all error output to /dev/null, which prevents the `YES (0)` normally included in the `security` command output from showing up in the Munki run log/output. The `&gt;` is an xml-escaped `>` character, so if you were running the command in a normal bash script it would look like this: `exec 2>/dev/null`

The other item you pointed out was a mistake, and should have been xml-escaped. The pkginfo has been corrected in the wiki now. Viewing the installcheck_script in MunkiAdmin should show `grep -q '<string>Escrow Buddy:Invoke,privileged</string>` but in the raw pkginfo file that snippet needs to be `grep -q '&lt;string&gt;Escrow Buddy:Invoke,privileged&lt;/string&gt;'`
