### ISSUE TITLE
Not Compatible with Jamf Connect

### ISSUE THREAD

**Issue by kylejericson** [macadmins/escrow-buddy#2]
Since this uses the authdatabase and macOS only supports one authdatabase at a time this wouldn't work with Jamf Connect.

**Comment by grahamgilbert** [comment]
Sorry that’s not correct. The authorization database can have as many mechanisms as required. Whether jamf connect’s installer does silly things or not I can’t say, but the installer for this project modifies the database in a sane way.

**Comment by kylejericson** [comment]
@grahamgilbert I'm happy to say I was wrong. I tested this workflow with a Jamf Connect enabled device and worked like a charm. Thanks for the good work on this.
