### ISSUE TITLE
Key is not being escrowed within Jamf

### ISSUE THREAD

**Issue by janzablox** [macadmins/escrow-buddy#8]
**Summary**

Followed the instructions, tested on a machine, but still no recovery key escrowed in Jamf.

**Steps to Reproduce**

Followed Wiki steps one-by-one, but not given desired result.

**Expected Behavior**

Recovery key should be escrowed within Jamf.

**Environment**

- Escrow Buddy version: [1.0.0]
- macOS version: [Sonoma 14.3.0]
- model [Apple M1 Pro]
- MDM version: [Jamf 11.1.1-t1701704198]

**Additional Context**

The one thing that may not be setup correctly is the [FDERecoveryKeyEscrow] payload. We have FileVault setup using a Configuration Profile, with the Security & Privacy > FileVault payload. I will include a screenshot. Is this the same as the FDERecoveryKeyEscrow payload mentioned in Step 1 of the Wiki? Also, for PKG download. Do I only need the PKG, or also the ZIP (Source Code) files?

<img width="1546" alt="Screenshot 2024-01-26 at 4 14 18 PM" src="https://github.com/macadmins/escrow-buddy/assets/132941181/8d3f9b31-2ab8-4c8b-abef-8b0ee82239e0">

**Comment by homebysix** [comment]
Hi @janzablox — the screenshot looks correct, but you may want to check on the affected Mac whether the escrow profile was actually received. If it was, you should see some output from this command:

```
profiles -Cv | grep -E 'type\s+= com.apple.security.FDERecoveryKeyEscrow'
```

If that's not the issue you might want to check the [logs](https://github.com/macadmins/escrow-buddy/wiki/FAQ#how-do-i-view-escrow-buddys-logs) and report what you find there.

**Comment by janzablox** [comment]
> Hi @janzablox — the screenshot looks correct, but you may want to check on the affected Mac whether the escrow profile was actually received. If it was, you should see some output from this command:
> If that's not the issue you might want to check the and report what you find there.

I forgot to mention, I also setup the EA which shows if the _Escrow Buddy authdb status_: is **Configured** - And it indeed was configured for this system. Upon checking JSS again, it looks like the key escrowed properly. So i'm not sure why it was so delayed, or what happened exactly.

For the logs, is that viewed via terminal directly from the affected machine?

**Comment by homebysix** [comment]
Either from the affected machine in Terminal or from another machine connected to the affected one using SSH.

Retrieval of the key happens during Jamf recon, so there may be a delay depending on your recon schedule. See [this post](https://www.elliotjordan.com/posts/filevault-escrow-daemon/) for a tip on speeding that up.

**Comment by janzablox** [comment]
The key randomly escrowed to Jamf at a later time, so you can close this!

**Comment by homebysix** [comment]
Sounds good. As mentioned in [this FAQ](https://github.com/macadmins/escrow-buddy/wiki/FAQ#how-long-after-login-should-the-recovery-key-appear-in-my-mdm), the key needs a `SecurityInfo` MDM command response before it will be escrowed to your MDM. For Jamf, this happens at recon/inventory update. Personally, I have an inventory update policy that runs once daily, in addition to the WatchPaths daemon mentioned in the post linked above.
