### ISSUE TITLE
Stuck in a boot loop after macOS Software Update

### ISSUE THREAD

**Issue by janzablox** [macadmins/escrow-buddy#9]
**Summary**

This may be a coincidence, but just wanted to report it in case there was a bug. I deployed Escrow Buddy to a system and it showed up as "Configured" within the Jamf EA (Escrow Buddy authdb status). I restarted with no issue, but noticed when I logged back into the system, it prompted (within System Settings) to update macOS to 13.6.4 from 13.5.1. When trying to install the update, it got stuck in a bootloop. Before even getting to the login screen, it prompts to enter a password for the Disk (looks like a FileVault prompt). Upon entering the password, it restarts and back to the same prompt. I've also tried macOS Recovery, including First Aid and reinstall macOS Ventura, but upon Reinstalling macOS Ventura through Recovery, it gives an error: **This operation couldn't be completed: (_com.apple.BuildInfo.preflight.error error 21._)** - At that point I tried SMC/NVRAM Resets, Safe Mode, and Internet Recovery. I still either get the FileVault Prompt to enter my password, which then bootloops, or the preflight error (when trying to reinstall macOS via Recovery).

**Steps to Reproduce**

- Install/configure Escrow buddy
- Restarted MacBook
- Ran update to latest version of Ventura
- Upon restart, boot loop occurs.

**Expected Behavior**

No boot loop, and only an escrowed Key.

**Environment**

- Escrow Buddy version: [e.g. 1.0.0]
- macOS version: [e.g. Ventura 13.5.1]
- MacBook Pro (13-inch, 2018)
- MDM version: [Jamf Version 11.1.1-t1701704198]

**Additional Context**

I've added some screenshots of the FileVault prompt and preflight error.
![IMG_4067](https://github.com/macadmins/escrow-buddy/assets/132941181/93aff588-c4f9-489a-ac4f-50a03d18e63e)
![IMG_4066](https://github.com/macadmins/escrow-buddy/assets/132941181/9dce8114-ffd8-4d19-9b1b-b7883db453b1)

**Comment by homebysix** [comment]
Hi @janzablox - This doesn't seem like a series of symptoms that Escrow Buddy could be responsible for. However just to be thorough, would you mind running through [these steps](https://github.com/macadmins/escrow-buddy/wiki/Recovery) to remove Escrow Buddy from the authorization database on the affected Mac? If the issues persist after the authdb has been reset to its default, I think it's likely the issue has a different cause.

**Comment by janzablox** [comment]
> Hi @janzablox - This doesn't seem like a series of symptoms that Escrow Buddy could be responsible for. However just to be thorough, would you mind running through [these steps](https://github.com/macadmins/escrow-buddy/wiki/Recovery) to remove Escrow Buddy from the authorization database on the affected Mac?

Which "Disk" should we be selecting to "Mount" the drive? Because most selections only give the option to "Unmount", not "Mount".
![Screenshot 2024-01-31 at 9 38 40 AM](https://github.com/macadmins/escrow-buddy/assets/132941181/749945fc-2d73-48b2-b204-8e691fac5908)

**Comment by homebysix** [comment]
It looks like `Macintosh HD` is already mounted in your screenshot. You should be OK to proceed to steps 4 and 5, where you delete specific files in Terminal from `/Volumes/Macintosh HD/var/db`.

**Comment by janzablox** [comment]
I didn't get the desired output within Step 5:
```
 auth.db
 auth.db-shm
 auth.db-wal
```
It seems this may be unrelated to Escrow Buddy. I also couldn't reproduce the problem on another machine, so maybe it was a botched macOS upgrade.

![Screenshot 2024-01-31 at 2 13 31 PM](https://github.com/macadmins/escrow-buddy/assets/132941181/c403c678-a4c6-4c34-8668-62d44adfadf7)
